server:
  port: 8082
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh
ms:
  order:
    category:
      price: 4000
spring:
  rabbitmq:
    host: localhost
    port: 5672
