---
emp: 
  id: 1
  name: mk dev update
  address: jamni
server:
  port: 8081
spring:
  config: 
    activate: 
      on-profile: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/pharmacy
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
...
---
emp: 
  id: 2
  name: mk test
  address: jamni
server:
  port: 8081
spring:
  config: 
    activate: 
      on-profile: test
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/pharmacy
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
...
---
emp: 
  id: 3
  name: mk prod update
  address: jamni
server:
  port: 8081
spring:
  config: 
    activate: 
      on-profile: prod
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/pharmacy
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
...
