server:
  port: 8888
  servlet:
    # Customize config server URL context path http://localhost:8888/config
    context-path: /config
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mithilesh108/MS-ConfigServer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/