server:
  port: 8762
  servlet:
    # Customize Eureka server URL context path http://localhost:8762/admin
    context-path: /admin
spring:
  application:
    name: CUSTOMER-ORDER-EUREKA-SERVER
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false