server:
  port: 8761
  servlet:
    application-display-name: qqqqq
    # Customize Eureka server URL context path http://localhost:8762/admin
    #context-path: /admin
spring:
  application:
    name: CUSTOMER-ORDER-EUREKA-SERVER
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false